scp \
    EventYields_presel/plots/nVert.pdf \
    EventYields_presel/plots/nVert_noPU.pdf \
    EventYields_presel/plots/mZee.pdf \
    EventYields_presel/plots/mZmm.pdf \
    EventYields_presel/plots/ptLept0_log.pdf \
    EventYields_presel/plots/ptLept1_log.pdf \
    EventYields_presel/plots/ptZ_log.pdf \
    EventYields_presel/plots/ptGamma_log.pdf \
    EventYields_presel/plots/ptgOmZg_bossCut.pdf \
    EventYields_v0/eff_ptCut.pdf \
    EventYields_v0/limit_Zllgamma.pdf \
    EventYields_v0/limit_Zgamma.pdf \
    plotsGenEfficiency/genresp.pdf \
    plotsGenEfficiency/genreso.pdf \
    plotsGenEfficiency/geneff_all.pdf \
    genAcceptance/genAcceptance.pdf \
    genAcceptance/cutEffSignal.pdf \
    genAcceptanceTimesEfficiency.pdf \
    massWeightCompare_log.pdf \
    EventYields_presel/syst*pdf \
    lxplus.cern.ch:~/tdr2/notes/AN-16-057/trunk/figures/
